### managed by Ansible

monitoring:
   - service: Check_Influx_Report
     check: local
     item: check_influx_report
     influx_query: 'SELECT * FROM cpu WHERE "host" =~ /%s/ and time > now() - 5m'
     influx_db: ft_ed_core
     influx_host: "http://influxdb.locaweb.com.br/query?"
     influx_user: monitoring
     influx_password: "c86758816b744bb7f2772b0ef7b53bd5"
     sla: false
     priority: 3

